// <auto-generated />
using Com.Kana.Service.Upload.Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Com.Kana.Service.Upload.Lib.Migrations
{
    [DbContext(typeof(UploadDbContext))]
    [Migration("20220628081542_addMasteritem")]
    partial class addMasteritem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<bool>("CalculateGroupPrice");

                    b.Property<string>("CogsGIAccountNo");

                    b.Property<bool>("ControlQuality");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DefaultDiscount");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("GoodTransitGIAccountNo");

                    b.Property<string>("InventoryGIAccountNo");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemCategoryName");

                    b.Property<string>("ItemType");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<bool>("ManageExpired");

                    b.Property<bool>("ManageSN");

                    b.Property<double>("MinimumQuantity");

                    b.Property<double>("MinimumQuantityReorder");

                    b.Property<string>("Name");

                    b.Property<string>("No");

                    b.Property<string>("Notes");

                    b.Property<double>("PercentTaxable");

                    b.Property<string>("PreferedVendorName");

                    b.Property<bool>("PrintDetailGroup");

                    b.Property<string>("PurchaseRetGIAccountNo");

                    b.Property<double>("Ratio2");

                    b.Property<double>("Ratio3");

                    b.Property<double>("Ratio4");

                    b.Property<double>("Ratio5");

                    b.Property<string>("SalesDiscountGIAccountNo");

                    b.Property<string>("SalesGIAccountNo");

                    b.Property<string>("SalesRetGIAccountNo");

                    b.Property<string>("SerialNumberType");

                    b.Property<bool>("Subtituted");

                    b.Property<string>("SubtitutedItemNo");

                    b.Property<string>("Tax1Name");

                    b.Property<string>("Tax2Name");

                    b.Property<string>("Tax3Name");

                    b.Property<string>("Tax4Name");

                    b.Property<double>("TypeAutoNumber");

                    b.Property<string>("UId")
                        .HasMaxLength(255);

                    b.Property<string>("UnBilledGIAccountNo");

                    b.Property<string>("Unit1Name");

                    b.Property<string>("Unit2Name");

                    b.Property<double>("Unit2Price");

                    b.Property<string>("Unit3Name");

                    b.Property<double>("Unit3Price");

                    b.Property<string>("Unit4Name");

                    b.Property<double>("Unit4Price");

                    b.Property<string>("Unit5Name");

                    b.Property<double>("Unit5Price");

                    b.Property<double>("UnitPrice");

                    b.Property<string>("UpcNo");

                    b.Property<bool>("UsePPn");

                    b.Property<bool>("UseWholesalePrice");

                    b.Property<double>("VendorPrice");

                    b.Property<string>("VendorUnitName");

                    b.HasKey("Id");

                    b.ToTable("AccuItems");
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccuItemId");

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DetailName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemNo");

                    b.Property<string>("ItemUnitName");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("Quantity");

                    b.Property<string>("Status");

                    b.Property<string>("UId")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("AccuItemId");

                    b.ToTable("AccuItemDetailGroups");
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailOpenBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccuItemId");

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("AsOf");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemUnitName");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("Quantity");

                    b.Property<string>("Status");

                    b.Property<string>("UId")
                        .HasMaxLength(255);

                    b.Property<double>("UnitCost");

                    b.Property<string>("WarehouseName");

                    b.HasKey("Id");

                    b.HasIndex("AccuItemId");

                    b.ToTable("AccuItemDetailOpenBalances");
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailSerialNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccuItemDetailOpenBalanceId");

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<DateTimeOffset>("ExpiredDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("Quantity");

                    b.Property<string>("SerialNumberNo");

                    b.Property<string>("Status");

                    b.Property<string>("UId")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("AccuItemDetailOpenBalanceId");

                    b.ToTable("AccuItemDetailSerialNumbers");
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailGroup", b =>
                {
                    b.HasOne("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItem", "AccuItem")
                        .WithMany("DetailGroup")
                        .HasForeignKey("AccuItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailOpenBalance", b =>
                {
                    b.HasOne("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItem", "AccuItem")
                        .WithMany("DetailOpenBalance")
                        .HasForeignKey("AccuItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailSerialNumber", b =>
                {
                    b.HasOne("Com.Kana.Service.Upload.Lib.Models.AccurateIntegration.AccuItemModel.AccuItemDetailOpenBalance", "DetailOpenBalance")
                        .WithMany("DetailSerialNumber")
                        .HasForeignKey("AccuItemDetailOpenBalanceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
